# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose


version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fleetdb
      SPRING_DATASOURCE_USERNAME: fleet-postgres
      SPRING_DATASOURCE_PASSWORD: test

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: fleet-postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data




