server:
  port: 8080
  address: 0.0.0.0  # Wichtig, damit Spring Boot im Docker auf allen Interfaces hört

spring:
  application:
    name: vehicle-service

  datasource:
    url: jdbc:postgresql://postgres:5432/fleetdb  # "postgres" ist der Service-Name im Docker-Netzwerk
    username: fleetuser
    password: fleetpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Für DEV: automatische Schema-Anpassung
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true  # Für schön formatiertes JSON

logging:
  level:
    root: info
    com.fleet: debug     # Detailliertere Logs für dein Package

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
