server:
  port: 8081

spring:
  application:
    name: vehicle-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fleetdb
    username: fleetuser
    password: fleetpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true

  security:
    user:
      name: adminballs
      password: admin123

logging:
  level:
    root: info
    com.fleet: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
