server:
  port: 8081

spring:
  application:
    name: vehicle-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fleetdb
    username: fleet-postgres
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update           # F?r DEV: auto-create/update Tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true        # F?r sch?n formatiertes JSON

logging:
  level:
    root: info
    com.fleet: debug             # Dein Package: ausf?hrlichere Logs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
